/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.introduccioned;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class VentanaContadores extends javax.swing.JFrame {
    
    
    int [] tamañoMenores;    
    int i=0;
    int [] tamañoMayores;
    int c=0; 
    int [] tamañoAncianos; 
    int a=0; 
    
    
    
     
    

    /**
     * Creates new form VentanaContadores
     */
    public VentanaContadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Create = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        tamaño = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        Create.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CreateKeyTyped(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        tamaño.setText("Tamaño");
        tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamaño)
                    .addComponent(consultar)
                    .addComponent(Create))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(tamaño)
                .addGap(41, 41, 41)
                .addComponent(Create)
                .addGap(45, 45, 45)
                .addComponent(consultar)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
       
        while (i < tamañoMenores.length || c < tamañoMayores.length || a < tamañoAncianos.length){
           
            //esto era lo que tenías antes de validar: 
            //int edad=Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Escriba su edad"));  
            
   
            String string = JOptionPane.showInputDialog(rootPane, "Escriba su edad");
            int edad = validateNumbers(string);  
    
            
            if (edad < 18 && i < tamañoMenores.length){
                tamañoMenores [i] = edad;
                i++; 
                JOptionPane.showMessageDialog(rootPane, "Usted es menor de edad");
                if (i == tamañoMenores.length) {
                    JOptionPane.showMessageDialog(rootPane, "Se ha alcanzado el límite máximo de menores.");
                }
            } else if (edad >=18 && edad < 60 && c < tamañoMayores.length){
                tamañoMayores [c] = edad;
                c++; 
                JOptionPane.showMessageDialog(rootPane, "Usted es adulto");
                if (c == tamañoMayores.length) {
                    JOptionPane.showMessageDialog(rootPane, "Se ha alcanzado el límite máximo de mayores.");
                }
            } else if (edad >= 60 && a < tamañoAncianos.length ){
                tamañoAncianos [a] = edad; 
                a++; 
                JOptionPane.showMessageDialog(rootPane, "Usted es mayor de edad");
                if (a == tamañoAncianos.length) {
                JOptionPane.showMessageDialog(rootPane, "Se ha alcanzado el límite máximo de ancianos.");
            }
            }  
        }
        
        
        
        
        
    }//GEN-LAST:event_CreateActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        
        
        String resultadoMenores = "Menores de edad: ";
        for (int j = 0; j < i; j++) {
            resultadoMenores += tamañoMenores[j] + " ";
        }
        
        String resultadoAdultos = "Adultos: ";
        for (int j = 0; j < c; j++) {
            resultadoAdultos += tamañoMayores[j] + " ";
        }
        
        String resultadoAncianos = "Ancianos: ";
        for (int j = 0; j < a; j++) {
            resultadoAncianos += tamañoAncianos[j] + " ";
        }
        
        JOptionPane.showMessageDialog(null, resultadoMenores + "\n" + resultadoAdultos + "\n" + resultadoAncianos);
        
    }//GEN-LAST:event_consultarActionPerformed

    private void tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoActionPerformed
        // TODO add your handling code here:
        int tamañoMenoresInt = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese el tamaño del arreglo de menores"));
        int tamañoMayoresInt = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese el tamaño del arreglo de adultos"));
        int tamañoAncianosInt = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese el tamaño del arreglo de ancianos"));
        
        //tamañoMenores = new int [tamañoMenoresInt];
        //tamañoMayores = new int [tamañoMayoresInt];
        //tamañoAncianos = new int [tamañoAncianosInt]; 
        
        if (tamañoMenoresInt > 0 && tamañoMayoresInt > 0 && tamañoAncianosInt > 0) {
            tamañoMenores = new int[tamañoMenoresInt];
            tamañoMayores = new int[tamañoMayoresInt];
            tamañoAncianos = new int[tamañoAncianosInt]; 
        } else {
        JOptionPane.showMessageDialog(rootPane, "Error, solo se permiten números");
        }   
        
        
        
        
        
       
    }//GEN-LAST:event_tamañoActionPerformed

   
    private int validateNumbers (String string){
       while (!isNumeric (string)){  //funcion por si no es numerico 
           string = JOptionPane.showInputDialog(rootPane, "Error, solo se permiten números");
       }
       return Integer.parseInt(string);  //convertir el string a entero 
    }
    
    public static boolean isNumeric(String string2) {
    if (string2 == null || string2.isEmpty()) {  //para ver si la cadena está vacía o no 
        return false;
    }
    try {
        Integer.parseInt(string2);  // Cambia a Integer para validar enteros
        return true;  // 
    } catch (NumberFormatException nfe) {
        return false;  // bota excepción si no es un número entero válido
    }
}

    
    
    private void CreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateKeyTyped

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton consultar;
    private javax.swing.JButton tamaño;
    // End of variables declaration//GEN-END:variables
}
