
package com.mycompany.nodosmetodos;

import javax.swing.JOptionPane;


public class Jframe extends javax.swing.JFrame {

    //creo el objeto de la clase principal:
    
    NodosMetodos objlista = new NodosMetodos();
    
    
    
    
    public Jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertarAinicio = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        promedio = new javax.swing.JTextField();
        indiceButton = new javax.swing.JButton();
        nameButton = new javax.swing.JButton();
        edadButton = new javax.swing.JButton();
        promedioButton = new javax.swing.JButton();
        insertarAfinal = new javax.swing.JButton();
        soloTextoNombre = new javax.swing.JLabel();
        soloTextoEdad = new javax.swing.JLabel();
        soloTextoPromedio = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insertarAinicio.setText("Crear lista insertando al inicio");
        insertarAinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarAinicioActionPerformed(evt);
            }
        });

        indiceButton.setText("Insertar después de índice");
        indiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceButtonActionPerformed(evt);
            }
        });

        nameButton.setText("Insertar después del nombre");

        edadButton.setText("Insertar después de la edad");

        promedioButton.setText("Insertar después del promedio");

        insertarAfinal.setText("insertando al final");
        insertarAfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarAfinalActionPerformed(evt);
            }
        });

        soloTextoNombre.setText("Nombre");

        soloTextoEdad.setText("Edad");

        soloTextoPromedio.setText("Promedio");

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(soloTextoNombre)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(soloTextoEdad)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(soloTextoPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edad)
                                .addGap(140, 140, 140)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertarAinicio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(insertarAfinal)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edadButton)
                                    .addComponent(nameButton)
                                    .addComponent(indiceButton))
                                .addGap(19, 19, 19))
                            .addComponent(promedioButton))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultar)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarAinicio)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soloTextoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarAfinal)
                    .addComponent(soloTextoEdad)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soloTextoPromedio)
                    .addComponent(consultar))
                .addGap(41, 41, 41)
                .addComponent(indiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promedioButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarAinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarAinicioActionPerformed
        objlista.insertarNodoAlInicio(nombre.getText(), Integer.parseInt(edad.getText()), Float.parseFloat(promedio.getText()));
        //ANOTACIÓN MUY IMPORTANTE: ahí puse nombre, edad, y promedio exactamente de esa forma 
        //porque así llamé a las variables a las que les corresponde esos botones,
        //que es este caso son text field 
        
        //variables que usaré para insertar después del... (indice,edad,nombre y promedio)
        indiceButton.setEnabled(true);
        nameButton.setEnabled(true);
        edadButton.setEnabled(true);
        promedioButton.setEnabled(true);
        
        
        
    }//GEN-LAST:event_insertarAinicioActionPerformed

    private void insertarAfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarAfinalActionPerformed
        objlista.insertarNodoAlFinal(nombre.getText(), Integer.parseInt(edad.getText()), Float.parseFloat(promedio.getText()));
        
        indiceButton.setEnabled(true);
        nameButton.setEnabled(true);
        edadButton.setEnabled(true);
        promedioButton.setEnabled(true);
    }//GEN-LAST:event_insertarAfinalActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        objlista.consultar();
    }//GEN-LAST:event_consultarActionPerformed

    private void indiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceButtonActionPerformed
        //aquí invoco el método de insertar después del índice 
        objlista.insertarEnIndice(nombre.getText(), Integer.parseInt(edad.getText()), Float.parseFloat(promedio.getText()),validateIntInput(JOptionPane.showInputDialog("Ingrese el indice:")) );
        
    }//GEN-LAST:event_indiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe().setVisible(true);
            }
        }); 
    }
    
    //VALIDACIÓN 
    public int validateIntInput(String str) {
        while (isNumber(str)==false) {
            str = JOptionPane.showInputDialog("Ingrese un número válido mayor a cero:");
        }
        return Integer.parseInt(str);
    }
    
    public static boolean isNumber(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar;
    private javax.swing.JTextField edad;
    private javax.swing.JButton edadButton;
    private javax.swing.JButton indiceButton;
    private javax.swing.JButton insertarAfinal;
    private javax.swing.JButton insertarAinicio;
    private javax.swing.JButton nameButton;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField promedio;
    private javax.swing.JButton promedioButton;
    private javax.swing.JLabel soloTextoEdad;
    private javax.swing.JLabel soloTextoNombre;
    private javax.swing.JLabel soloTextoPromedio;
    // End of variables declaration//GEN-END:variables
}
